export  const newsData = [
    {   id:1, 
        image:"/image/img1.png",
        title:"Visited Dapsone Sirap Coffee, The Product of Robusta in Central Java",
        time:"4 min",
        date:"August 19,2024",
        disc1: "The moment you step into Coffee Shop Mews, you're transported to a different world. The cozy, intimate setting with its exposed brick walls, vintage wooden furniture, and eclectic mix of artwork gives the place a bohemian charm. Soft jazz music plays in        the background, enhancing the relaxed vibe, making it the perfect spot to unwind with a good book or catch up with friends.",
        disc2: "One of the standout features of Coffee Shop Mews is its delightful courtyard. Tucked away behind the main seating area, this secluded outdoor space is adorned with fairy lights and potted plants, creating a serene oasis in the middle of the city. It's the perfect place to enjoy a sunny morning or a cool evening with your favorite brew.",
        disc3: "At Coffee Shop Mews, coffee is more than just a beverage—it's a craft. The baristas here are true artisans, taking immense pride in every cup they serve. Whether you're a fan of a robust espresso or a creamy latte, you'll find that each drink is meticulously prepared to perfection.",
        disc4: "The shop sources its beans from sustainable farms around the world, ensuring that every cup not only tastes great but also supports ethical practices. Their signature blends, such as the rich and chocolatey 'Midnight Mews' or the bright and fruity 'Sunrise Alley,' offer unique flavor profiles that keep customers coming back for more.",
        disc5: "For those looking to try something different, the menu features a range of artisanal coffee creations. From lavender-infused lattes to honey cinnamon cappuccinos, there's always something new and exciting to tantalize your taste buds.",
        disc6: "While coffee is the star of the show, Coffee Shop Mews offers an array of delicious treats and light bites to complement your drink. Their pastries, baked fresh daily, are a must-try. From flaky croissants to decadent brownies, there's something to satisfy every sweet tooth.",
        disc7: "For those in need of something more substantial, the shop also offers a selection of savory items. Their avocado toast, topped with cherry tomatoes and a sprinkle of feta, is a popular choice for a light yet satisfying meal. The menu also features seasonal soups and salads, making it a great spot for lunch.",
    },
    {  id:2,
        image:"/image/img2.png",
        title:"Cold Brew Coffee, How to Drink Cold Coffee is More Enjoyable",
        time:"4 min",
        date:"August 19,2024",
        disc1: "The moment you step into Coffee Shop Mews, you're transported to a different world. The cozy, intimate setting with its exposed brick walls, vintage wooden furniture, and eclectic mix of artwork gives the place a bohemian charm. Soft jazz music plays in        the background, enhancing the relaxed vibe, making it the perfect spot to unwind with a good book or catch up with friends.",
        disc2: "One of the standout features of Coffee Shop Mews is its delightful courtyard. Tucked away behind the main seating area, this secluded outdoor space is adorned with fairy lights and potted plants, creating a serene oasis in the middle of the city. It's the perfect place to enjoy a sunny morning or a cool evening with your favorite brew.",
        disc3: "At Coffee Shop Mews, coffee is more than just a beverage—it's a craft. The baristas here are true artisans, taking immense pride in every cup they serve. Whether you're a fan of a robust espresso or a creamy latte, you'll find that each drink is meticulously prepared to perfection.",
        disc4: "The shop sources its beans from sustainable farms around the world, ensuring that every cup not only tastes great but also supports ethical practices. Their signature blends, such as the rich and chocolatey 'Midnight Mews' or the bright and fruity 'Sunrise Alley,' offer unique flavor profiles that keep customers coming back for more.",
        disc5: "For those looking to try something different, the menu features a range of artisanal coffee creations. From lavender-infused lattes to honey cinnamon cappuccinos, there's always something new and exciting to tantalize your taste buds.",
        disc6: "While coffee is the star of the show, Coffee Shop Mews offers an array of delicious treats and light bites to complement your drink. Their pastries, baked fresh daily, are a must-try. From flaky croissants to decadent brownies, there's something to satisfy every sweet tooth.",
        disc7: "For those in need of something more substantial, the shop also offers a selection of savory items. Their avocado toast, topped with cherry tomatoes and a sprinkle of feta, is a popular choice for a light yet satisfying meal. The menu also features seasonal soups and salads, making it a great spot for lunch.",
    },
    {  id:3,
        image:"/image/img3.png",
        title:"Meet Coffee Tonic, the Sensation of Drinking Coffee-Flavored Soda",
        time:"4 min",
        date:"August 19,2024",
        disc1: "The moment you step into Coffee Shop Mews, you're transported to a different world. The cozy, intimate setting with its exposed brick walls, vintage wooden furniture, and eclectic mix of artwork gives the place a bohemian charm. Soft jazz music plays in        the background, enhancing the relaxed vibe, making it the perfect spot to unwind with a good book or catch up with friends.",
        disc2: "One of the standout features of Coffee Shop Mews is its delightful courtyard. Tucked away behind the main seating area, this secluded outdoor space is adorned with fairy lights and potted plants, creating a serene oasis in the middle of the city. It's the perfect place to enjoy a sunny morning or a cool evening with your favorite brew.",
        disc3: "At Coffee Shop Mews, coffee is more than just a beverage—it's a craft. The baristas here are true artisans, taking immense pride in every cup they serve. Whether you're a fan of a robust espresso or a creamy latte, you'll find that each drink is meticulously prepared to perfection.",
        disc4: "The shop sources its beans from sustainable farms around the world, ensuring that every cup not only tastes great but also supports ethical practices. Their signature blends, such as the rich and chocolatey 'Midnight Mews' or the bright and fruity 'Sunrise Alley,' offer unique flavor profiles that keep customers coming back for more.",
        disc5: "For those looking to try something different, the menu features a range of artisanal coffee creations. From lavender-infused lattes to honey cinnamon cappuccinos, there's always something new and exciting to tantalize your taste buds.",
        disc6: "While coffee is the star of the show, Coffee Shop Mews offers an array of delicious treats and light bites to complement your drink. Their pastries, baked fresh daily, are a must-try. From flaky croissants to decadent brownies, there's something to satisfy every sweet tooth.",
        disc7: "For those in need of something more substantial, the shop also offers a selection of savory items. Their avocado toast, topped with cherry tomatoes and a sprinkle of feta, is a popular choice for a light yet satisfying meal. The menu also features seasonal soups and salads, making it a great spot for lunch.",
    },
    {  id:4,
        image:"/image/img4.png",
        title:"Workshop Coffee Sharing Seassion",
        time:"4 min",
        date:"August 19,2024",
        disc1: "The moment you step into Coffee Shop Mews, you're transported to a different world. The cozy, intimate setting with its exposed brick walls, vintage wooden furniture, and eclectic mix of artwork gives the place a bohemian charm. Soft jazz music plays in        the background, enhancing the relaxed vibe, making it the perfect spot to unwind with a good book or catch up with friends.",
        disc2: "One of the standout features of Coffee Shop Mews is its delightful courtyard. Tucked away behind the main seating area, this secluded outdoor space is adorned with fairy lights and potted plants, creating a serene oasis in the middle of the city. It's the perfect place to enjoy a sunny morning or a cool evening with your favorite brew.",
        disc3: "At Coffee Shop Mews, coffee is more than just a beverage—it's a craft. The baristas here are true artisans, taking immense pride in every cup they serve. Whether you're a fan of a robust espresso or a creamy latte, you'll find that each drink is meticulously prepared to perfection.",
        disc4: "The shop sources its beans from sustainable farms around the world, ensuring that every cup not only tastes great but also supports ethical practices. Their signature blends, such as the rich and chocolatey 'Midnight Mews' or the bright and fruity 'Sunrise Alley,' offer unique flavor profiles that keep customers coming back for more.",
        disc5: "For those looking to try something different, the menu features a range of artisanal coffee creations. From lavender-infused lattes to honey cinnamon cappuccinos, there's always something new and exciting to tantalize your taste buds.",
        disc6: "While coffee is the star of the show, Coffee Shop Mews offers an array of delicious treats and light bites to complement your drink. Their pastries, baked fresh daily, are a must-try. From flaky croissants to decadent brownies, there's something to satisfy every sweet tooth.",
        disc7: "For those in need of something more substantial, the shop also offers a selection of savory items. Their avocado toast, topped with cherry tomatoes and a sprinkle of feta, is a popular choice for a light yet satisfying meal. The menu also features seasonal soups and salads, making it a great spot for lunch.",
    },
    {  id:5,
        image:"/image/img5.png",
        title:"Workshop Coffee Brewing",
        time:"4 min",
        date:"August 19,2024",
        disc1: "The moment you step into Coffee Shop Mews, you're transported to a different world. The cozy, intimate setting with its exposed brick walls, vintage wooden furniture, and eclectic mix of artwork gives the place a bohemian charm. Soft jazz music plays in        the background, enhancing the relaxed vibe, making it the perfect spot to unwind with a good book or catch up with friends.",
        disc2: "One of the standout features of Coffee Shop Mews is its delightful courtyard. Tucked away behind the main seating area, this secluded outdoor space is adorned with fairy lights and potted plants, creating a serene oasis in the middle of the city. It's the perfect place to enjoy a sunny morning or a cool evening with your favorite brew.",
        disc3: "At Coffee Shop Mews, coffee is more than just a beverage—it's a craft. The baristas here are true artisans, taking immense pride in every cup they serve. Whether you're a fan of a robust espresso or a creamy latte, you'll find that each drink is meticulously prepared to perfection.",
        disc4: "The shop sources its beans from sustainable farms around the world, ensuring that every cup not only tastes great but also supports ethical practices. Their signature blends, such as the rich and chocolatey 'Midnight Mews' or the bright and fruity 'Sunrise Alley,' offer unique flavor profiles that keep customers coming back for more.",
        disc5: "For those looking to try something different, the menu features a range of artisanal coffee creations. From lavender-infused lattes to honey cinnamon cappuccinos, there's always something new and exciting to tantalize your taste buds.",
        disc6: "While coffee is the star of the show, Coffee Shop Mews offers an array of delicious treats and light bites to complement your drink. Their pastries, baked fresh daily, are a must-try. From flaky croissants to decadent brownies, there's something to satisfy every sweet tooth.",
        disc7: "For those in need of something more substantial, the shop also offers a selection of savory items. Their avocado toast, topped with cherry tomatoes and a sprinkle of feta, is a popular choice for a light yet satisfying meal. The menu also features seasonal soups and salads, making it a great spot for lunch.",
    },
    {  id:6,
        image:"/image/img1.png",
        title:"Visited Dapsone Sirap Coffee, The Product of Robusta in Central Java",
        time:"4 min",
        date:"August 19,2024",
        disc1: "The moment you step into Coffee Shop Mews, you're transported to a different world. The cozy, intimate setting with its exposed brick walls, vintage wooden furniture, and eclectic mix of artwork gives the place a bohemian charm. Soft jazz music plays in        the background, enhancing the relaxed vibe, making it the perfect spot to unwind with a good book or catch up with friends.",
        disc2: "One of the standout features of Coffee Shop Mews is its delightful courtyard. Tucked away behind the main seating area, this secluded outdoor space is adorned with fairy lights and potted plants, creating a serene oasis in the middle of the city. It's the perfect place to enjoy a sunny morning or a cool evening with your favorite brew.",
        disc3: "At Coffee Shop Mews, coffee is more than just a beverage—it's a craft. The baristas here are true artisans, taking immense pride in every cup they serve. Whether you're a fan of a robust espresso or a creamy latte, you'll find that each drink is meticulously prepared to perfection.",
        disc4: "The shop sources its beans from sustainable farms around the world, ensuring that every cup not only tastes great but also supports ethical practices. Their signature blends, such as the rich and chocolatey 'Midnight Mews' or the bright and fruity 'Sunrise Alley,' offer unique flavor profiles that keep customers coming back for more.",
        disc5: "For those looking to try something different, the menu features a range of artisanal coffee creations. From lavender-infused lattes to honey cinnamon cappuccinos, there's always something new and exciting to tantalize your taste buds.",
        disc6: "While coffee is the star of the show, Coffee Shop Mews offers an array of delicious treats and light bites to complement your drink. Their pastries, baked fresh daily, are a must-try. From flaky croissants to decadent brownies, there's something to satisfy every sweet tooth.",
        disc7: "For those in need of something more substantial, the shop also offers a selection of savory items. Their avocado toast, topped with cherry tomatoes and a sprinkle of feta, is a popular choice for a light yet satisfying meal. The menu also features seasonal soups and salads, making it a great spot for lunch.",
    },
    {  id:7,
        image:"/image/img1.png",
        title:"Visited Dapsone Sirap Coffee, The Product of Robusta in Central Java",
        time:"4 min",
        date:"August 19,2024",
        disc1: "The moment you step into Coffee Shop Mews, you're transported to a different world. The cozy, intimate setting with its exposed brick walls, vintage wooden furniture, and eclectic mix of artwork gives the place a bohemian charm. Soft jazz music plays in        the background, enhancing the relaxed vibe, making it the perfect spot to unwind with a good book or catch up with friends.",
        disc2: "One of the standout features of Coffee Shop Mews is its delightful courtyard. Tucked away behind the main seating area, this secluded outdoor space is adorned with fairy lights and potted plants, creating a serene oasis in the middle of the city. It's the perfect place to enjoy a sunny morning or a cool evening with your favorite brew.",
        disc3: "At Coffee Shop Mews, coffee is more than just a beverage—it's a craft. The baristas here are true artisans, taking immense pride in every cup they serve. Whether you're a fan of a robust espresso or a creamy latte, you'll find that each drink is meticulously prepared to perfection.",
        disc4: "The shop sources its beans from sustainable farms around the world, ensuring that every cup not only tastes great but also supports ethical practices. Their signature blends, such as the rich and chocolatey 'Midnight Mews' or the bright and fruity 'Sunrise Alley,' offer unique flavor profiles that keep customers coming back for more.",
        disc5: "For those looking to try something different, the menu features a range of artisanal coffee creations. From lavender-infused lattes to honey cinnamon cappuccinos, there's always something new and exciting to tantalize your taste buds.",
        disc6: "While coffee is the star of the show, Coffee Shop Mews offers an array of delicious treats and light bites to complement your drink. Their pastries, baked fresh daily, are a must-try. From flaky croissants to decadent brownies, there's something to satisfy every sweet tooth.",
        disc7: "For those in need of something more substantial, the shop also offers a selection of savory items. Their avocado toast, topped with cherry tomatoes and a sprinkle of feta, is a popular choice for a light yet satisfying meal. The menu also features seasonal soups and salads, making it a great spot for lunch.",
    },
    {  id:8,
        image:"/image/img1.png",
        title:"Visited Dapsone Sirap Coffee, The Product of Robusta in Central Java",
        time:"4 min",
        date:"August 19,2024",
        disc1: "The moment you step into Coffee Shop Mews, you're transported to a different world. The cozy, intimate setting with its exposed brick walls, vintage wooden furniture, and eclectic mix of artwork gives the place a bohemian charm. Soft jazz music plays in        the background, enhancing the relaxed vibe, making it the perfect spot to unwind with a good book or catch up with friends.",
        disc2: "One of the standout features of Coffee Shop Mews is its delightful courtyard. Tucked away behind the main seating area, this secluded outdoor space is adorned with fairy lights and potted plants, creating a serene oasis in the middle of the city. It's the perfect place to enjoy a sunny morning or a cool evening with your favorite brew.",
        disc3: "At Coffee Shop Mews, coffee is more than just a beverage—it's a craft. The baristas here are true artisans, taking immense pride in every cup they serve. Whether you're a fan of a robust espresso or a creamy latte, you'll find that each drink is meticulously prepared to perfection.",
        disc4: "The shop sources its beans from sustainable farms around the world, ensuring that every cup not only tastes great but also supports ethical practices. Their signature blends, such as the rich and chocolatey 'Midnight Mews' or the bright and fruity 'Sunrise Alley,' offer unique flavor profiles that keep customers coming back for more.",
        disc5: "For those looking to try something different, the menu features a range of artisanal coffee creations. From lavender-infused lattes to honey cinnamon cappuccinos, there's always something new and exciting to tantalize your taste buds.",
        disc6: "While coffee is the star of the show, Coffee Shop Mews offers an array of delicious treats and light bites to complement your drink. Their pastries, baked fresh daily, are a must-try. From flaky croissants to decadent brownies, there's something to satisfy every sweet tooth.",
        disc7: "For those in need of something more substantial, the shop also offers a selection of savory items. Their avocado toast, topped with cherry tomatoes and a sprinkle of feta, is a popular choice for a light yet satisfying meal. The menu also features seasonal soups and salads, making it a great spot for lunch.",
    },
    {  id:9,
        image:"/image/img1.png",
        title:"Visited Dapsone Sirap Coffee, The Product of Robusta in Central Java",
        time:"4 min",
        date:"August 19,2024",
        disc1: "The moment you step into Coffee Shop Mews, you're transported to a different world. The cozy, intimate setting with its exposed brick walls, vintage wooden furniture, and eclectic mix of artwork gives the place a bohemian charm. Soft jazz music plays in        the background, enhancing the relaxed vibe, making it the perfect spot to unwind with a good book or catch up with friends.",
        disc2: "One of the standout features of Coffee Shop Mews is its delightful courtyard. Tucked away behind the main seating area, this secluded outdoor space is adorned with fairy lights and potted plants, creating a serene oasis in the middle of the city. It's the perfect place to enjoy a sunny morning or a cool evening with your favorite brew.",
        disc3: "At Coffee Shop Mews, coffee is more than just a beverage—it's a craft. The baristas here are true artisans, taking immense pride in every cup they serve. Whether you're a fan of a robust espresso or a creamy latte, you'll find that each drink is meticulously prepared to perfection.",
        disc4: "The shop sources its beans from sustainable farms around the world, ensuring that every cup not only tastes great but also supports ethical practices. Their signature blends, such as the rich and chocolatey 'Midnight Mews' or the bright and fruity 'Sunrise Alley,' offer unique flavor profiles that keep customers coming back for more.",
        disc5: "For those looking to try something different, the menu features a range of artisanal coffee creations. From lavender-infused lattes to honey cinnamon cappuccinos, there's always something new and exciting to tantalize your taste buds.",
        disc6: "While coffee is the star of the show, Coffee Shop Mews offers an array of delicious treats and light bites to complement your drink. Their pastries, baked fresh daily, are a must-try. From flaky croissants to decadent brownies, there's something to satisfy every sweet tooth.",
        disc7: "For those in need of something more substantial, the shop also offers a selection of savory items. Their avocado toast, topped with cherry tomatoes and a sprinkle of feta, is a popular choice for a light yet satisfying meal. The menu also features seasonal soups and salads, making it a great spot for lunch.",
    },
]